# NOTE: These settings can be overridden by environment variables as well, in
# particular:
#
#    PGHOST
#    PGPORT
#    PGUSER
#    PGPASS
#    PGDATABASE

Default: &defaults
  user: a-league
  password: a-league
  host: localhost
  port: 5432
  database: a-league
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: a-league_test
  <<: *defaults

Staging:
  database: a-league_staging
  poolsize: 100
  <<: *defaults

Production:
  database: a-league_production
  poolsize: 100
  <<: *defaults
