Default: &defaults
  database: a-league.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: a-league_test.sqlite3
  <<: *defaults

Staging:
  database: a-league_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: a-league_production.sqlite3
  poolsize: 100
  <<: *defaults
